create table account_types (id  bigserial not null, monthly_fee numeric(19, 2), transaction_fee numeric(19, 2), type varchar(255), primary key (id));
create table cd_accounts (id  bigserial not null, created_on timestamp not null, balance numeric(19, 2), iban varchar(255) not null, expiration_date date not null, interest numeric(19, 2) not null, outcome_amount numeric(19, 2) not null, period_in_years int4 not null, type_id int8, user_id int8 not null, primary key (id));
create table checking_accounts (id  bigserial not null, created_on timestamp not null, balance numeric(19, 2), iban varchar(255) not null, type_id int8, user_id int8 not null, primary key (id));
create table loan_types (id  bigserial not null, consideration_fee numeric(19, 2) not null, interest_rate numeric(19, 2) not null, monthly_fee numeric(19, 2) not null, name varchar(255), primary key (id));
create table loans (id  bigserial not null, created_on timestamp not null, approved boolean not null, beginning_loan_amount numeric(19, 2) not null, due_date date not null, maturity_date date not null, monthly_payment numeric(19, 2) not null, period_in_months int4 not null, remaining_loan_amount numeric(19, 2) not null, total_amount_sum numeric(19, 2) not null, account_id int8 not null, type_id int8 not null, primary key (id));
create table roles (id  bigserial not null, role varchar(255), primary key (id));
create table transactions (id  bigserial not null, created_on timestamp not null, uuid VARCHAR not null, amount numeric(19, 2) not null, reason TEXT, type varchar(255), account_id int8, primary key (id));
create table users (id  bigserial not null, created_on timestamp not null, email varchar(255) not null, full_name varchar(255) not null, has_loan boolean default false not null, password varchar(255) not null, phone_number varchar(255), username varchar(255) not null, primary key (id));
create table users_roles (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table cd_accounts add constraint UK_2k7akumex8puigm5pnqdab71r unique (iban);
alter table checking_accounts add constraint UK_rjmxifkparedbeeex153pa77e unique (iban);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table cd_accounts add constraint FKj92n1u53epp4uxvdfydy630b9 foreign key (type_id) references account_types;
alter table cd_accounts add constraint FK65u4fhpkr7djtmx9ovex34069 foreign key (user_id) references users;
alter table checking_accounts add constraint FK7se6qaf55evv4v02afelq01pv foreign key (type_id) references account_types;
alter table checking_accounts add constraint FK31aele3dintsmmlfodaki8r3b foreign key (user_id) references users;
alter table loans add constraint FKajp9rmnqvg8l291d9qc0npglk foreign key (account_id) references checking_accounts;
alter table loans add constraint FKk5ld0bmden8fxcgjqgl76nf5i foreign key (type_id) references loan_types;
alter table transactions add constraint FK8euimpqfd44lygudtohsj0ugd foreign key (account_id) references checking_accounts;
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles;
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users;
